apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-auth
  namespace: dev-apps
  labels:
    app.kubernetes.io/name: postgresql
    homelab.io/environment: dev
    homelab.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-sm-dev
  target:
    name: postgresql-auth
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        POSTGRES_DB: appdb
        POSTGRES_USER: appuser
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: homelab-dev-postgres-password
    - secretKey: POSTGRES_URL
      remoteRef:
        key: homelab-dev-postgres-url
