apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sample-app-secret
  namespace: dev-apps
  labels:
    homelab.io/environment: dev
    homelab.io/component: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-sm-dev
  target:
    name: sample-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: APP_PASSWORD
      remoteRef:
        key: REPLACE_WITH_GCP_SECRET_NAME
