apiVersion: v1
kind: Secret
metadata:
  name: postgresql-auth
  namespace: dev-apps
  labels:
    app.kubernetes.io/name: postgresql
    homelab.io/environment: dev
    homelab.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: CHANGE-ME-ROTATE-IMMEDIATELY
