apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/serviceaccount-eso-gcp-dev.yaml
  - manifests/serviceaccount-eso-gcp-prd.yaml
  - manifests/clustersecretstore-gcp-dev.yaml
  - manifests/clustersecretstore-gcp-prd.yaml
  - manifests/rbac-externalsecret-manager-dev.yaml
  - manifests/rbac-externalsecret-manager-prd.yaml