apiVersion: v1
kind: Service
metadata:
  name: traefik-postgres
  namespace: kube-system
  labels:
    homelab.io/scope: cluster-shared
    homelab.io/component: ingress
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 192.168.15.0/24
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
