apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: prd-apps
  labels:
    app.kubernetes.io/name: myapp
    homelab.io/environment: prd
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
