apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-sm-prd
  labels:
    homelab.io/environment: prd
    homelab.io/component: secrets
spec:
  conditions:
    - namespaces:
        - prd-apps
  provider:
    gcpsm:
      projectID: REPLACE_WITH_GCP_PROJECT_ID
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: eso-gcp-sa-key-prd
            namespace: external-secrets
            key: service-account.json
