apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-sm-dev
  labels:
    homelab.io/environment: dev
    homelab.io/component: secrets
spec:
  conditions:
    - namespaces:
        - dev-apps
  provider:
    gcpsm:
      projectID: homelab-492918
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: eso-gcp-sa-key-dev
            namespace: external-secrets
            key: service-account.json
