apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-sm-dev
  labels:
    homelab.io/environment: dev
    homelab.io/component: secrets
spec:
  conditions:
    - namespaces:
        - dev-apps
  provider:
    gcpsm:
      projectID: homelab-492918
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/702302784311/locations/global/workloadIdentityPools/homelab-k3s-pool/providers/homelab-k3s-provider
          serviceAccountRef:
            name: eso-gcp-dev
            namespace: external-secrets
            audiences:
              - //iam.googleapis.com/projects/702302784311/locations/global/workloadIdentityPools/homelab-k3s-pool/providers/homelab-k3s-provider
