apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-gcp-dev
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    homelab.io/environment: dev
    homelab.io/component: secrets
