apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-gcp-prd
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    homelab.io/environment: prd
    homelab.io/component: secrets
